# Stage 1: Create the runtime image
FROM amazoncorretto:17-alpine-jdk
WORKDIR /app

# Copy the built jar file from the build stage
COPY rootmaker-backend-0.0.1-SNAPSHOT.jar app.jar

# Expose the port the app runs on (default is 8080)
EXPOSE 8080

# Set the entrypoint to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
